"""Añadir nuevo campo a Candidato

Revision ID: 6c32683694b2
Revises: 
Create Date: 2024-08-01 09:32:33.391888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c32683694b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('administrador')
    with op.batch_alter_table('candidato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partido', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('nombre', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('apellido', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('correo', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('contrasena', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('estado_voto', sa.Boolean(), nullable=True))
        batch_op.drop_column('propuesta')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('propuesta', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('estado_voto')
        batch_op.drop_column('contrasena')
        batch_op.drop_column('correo')
        batch_op.drop_column('apellido')
        batch_op.drop_column('nombre')
        batch_op.drop_column('partido')

    op.create_table('administrador',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
